#!/usr/bin/env sh

if test -z "${*}"; then
  # Start a new interactive login shell if the user calls
  # this script with no arguments, eg: via docker ENDPOINT.
  exec sh -l
elif grep -Fxq "$(type -P "${1}")" /etc/shells; then
  # Executed only if the user requests a specific shell that
  # is available on the current system (see /etc/shells)
  exec "${@}"
else
  # Replicate the behaviour of `docker exec`, delegating
  # child reaping and signal handling to docker --init
  exec sh -l -c "${*}"
fi
